[build]
  command = "npm run build"        # Run build command
  publish = "dist"                 # Ensure this is the directory Vite outputs to
    

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 
